### ISSUE TITLE
Reuse fetching/error display logic

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#1061]
#### Summary

We recently introduced the `withRequest` hoc (see https://github.com/TheThingsNetwork/lorawan-stack/pull/1031) that encapsulates the common logic for handling requests and fetching/error state. 

#### Why do we need this?

We should adapt other views that share the same logic to be consistent accross the codebase

#### What is already there? What do you see now?

The `withRequest` hoc

#### What is missing? What do you want to see?

`withRequest` used in the views

the list of views to be refactored:
- [ ] [/views/application](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application/index.js) (#1064)
- [ ] [/views/gateway](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/gateway/index.js) (#1064)
- [ ] [/views/application-link](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-link/index.js) (#1064)
- [ ] [/views/device](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/device/index.js) (#1064)
- [x] [/views/gateway-collaborator-add](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/gateway-collaborator-add/index.js) (#1031)
- [x] [/views/gateway-collaborator-edit](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/gateway-collaborator-edit/index.js) (#1031)
- [x] [/views/application-collaborator-add](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-collaborator-add/index.js) (#1031)
- [x] [/views/application-collaborator-edit](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-collaborator-edit/index.js) (#1031)
- [x] [/views/gateway-api-key-add](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/gateway-api-key-add/index.js) (#1031)
- [x] [/views/gateway-api-key-edit](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/gateway-api-key-edit/index.js) (#1031)
- [x] [/views/application-api-key-add](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-api-key-add/index.js) (#1031)
- [x] [/views/application-api-key-edit](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-api-key-edit/index.js) (#1031)
- [x] [/views/application-integration-edit](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-integration-edit/index.js) (#1031)

#### Environment

browser(console)

#### How do you propose to implement this?

* Remove calls to load data in the `componentDidMount` method
* Remove check for the fetching state  in the `render` method
* Remove check for the error state in the `componentDidUpdate` method

Delegate this to `withRequest`

#### Can you do this yourself and submit a Pull Request?

yes
