### ISSUE TITLE
Console feature gaps v2/v3

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2230]
#### Summary
We need to organize our work towards closing the current feature gap of the v2 and v3 console. This umbrella issue keeps track of the progress.

#### Why do we need this?
- We should not work on completely new features until the v3 console can provide all features of v2 console.
- Organizing our process / roadmap

#### What is already there? What do you see now?
We already provide most of the features that users know from v2, but there are still some gaps.

##### General
- [ ] Profile settings (Name, Description, Email, Profile Picture, Delete own account) ⟶ #1422
- [ ] Providing Japanese and Chinese language version of the console ⟶ #2435
- [ ] Filters for event streams ⟶ #2231
- [x] Using maps to set location values ⟶ #1380

##### Applications
- [ ] Providing payload format testing (dry-running byte payloads through the payload formatted) ⟶ #2232
- [x] Providing template tiles for webhook integrations ⟶ #945 
- [x] Storage integration (TTI issue) [#1830](https://github.com/TheThingsIndustries/lorawan-stack/issues/)

##### End Devices
- [ ] Showing end device statuses in end device list ⟶ #2436
- [x] Showing the Device EUIs in the end device list ⟶ #2437
- [x] Showing end device last seen and frame counts in device overview ⟶ #2167 
- [ ] Resetting frame counts for end devices ⟶ #2434
- [x] Scheduling downlinks ⟶ #1948
- [x] Simulating uplinks ⟶ #2234
- [x] Setting frame counter widths ⟶ #2438

##### Gateways
- [ ] Setting and displaying gateway manufacturer info (Brand, Model, Antenna(s), etc) ⟶ #2441
- [x] Setting automatic update behavior ⟶ #2439
- [ ] Setting Indoor/Outdoor location flag ⟶ #2440
- [ ] Show "Last seen" when a gateway is offline

@htdvisser @johanstokking please review the list. There might be things in there that we actually don't want to add to v3, or in different form.

**Comment by johanstokking** [comment]
I'm very happy with the overview issue. And I think it's good to have the issues filed. We can then prioritize them and put them in the concerning milestones.

**Comment by kschiffer** [comment]
I filed all issues now. @laurensslats any specific priority you want us to respect?

**Comment by benolayinka** [comment]
@kschiffer how about creating users in the console? This is still CLI only

**Comment by kschiffer** [comment]
Yes but this is not a v2/v3 feature app. You can open a separate issue for this so we can track this.

**Comment by kschiffer** [comment]
I'll move this to the Backlog milestone since the individual issues are already prioritized correctly and this issue is more to keep track overall.

**Comment by johanstokking** [comment]
I think it's time to close this, especially because we have individual issues that can be tracked.
