### ISSUE TITLE
Console support for applications

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#24]
**Summary:** 
The console should provide functionality to manage applications, namely:
- listing applications (short and full overview)
	- list applications that the user has rights on (paginated) by default
- adding applications
- removing applications
- updating applications

**What is already there? What do you see now?**
Screen design for the application page.

**What is missing? What do you want to see?**
Components:
- [x] Table component
- [x] Sidebar navigation
- [x] Tabs
- [x] Data Panel #28
  - [x] As smaller widget for the overview page
  - [x] As full size component
- [x] Settings panel
- [ ] Autosuggest input for adding users (for collaborators page)
- [x] Safe inspector component with copy functionality 
- [x] Code editor (for payload formatters)

Pages:
- [x] Main application page to show a table of application for the user (paginated)
- [x] Page to add a new application.
- [x] Detailed view of an application where it can be updated/deleted.
- [x] Access Key management #142 
  - [x] List api keys
  - [x] Edit api keys
  - [x] Create api key
  - [x] Delete api key
- [x] Payload Formatters #71, #214 
  - [x] Javascript formatter
  - [x] GRPC service formatter
  - [x] CayenneLPP and none
- [x] Link to NS #214 
  - [x] Create application link
  - [x] Edit application link

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1065 by @bafonins
