### ISSUE TITLE
Console support for devices

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#25]
**Summary:** 
The console should provide functionality to manage devices per application (see https://github.com/TheThingsIndustries/lorawan-stack/issues/1065), namely:
- listing devices
	- list all devices (paginated) per application
	- search devices by ids per application
- add devices
- deleting devices
- updating devices
- adding locations for devices

**What is already there? What do you see now?**
Wireframes for the devices page

**What is missing? What do you want to see?**
- [x] Device support in the SDK -> #131 
- [x] Replacement of api stubs -> #236 
- [x] Entry in the side navigation when examining a particular application
- [x] Main device page with a table showing all registered devices under a specific application (paginated)
- [x] Device subview consisting of multiple section
  - [x] Setting up the subroute (tabs, route handling) -> via #376 
  - [x] Overview -> #376 
  - [x] Device level payload formatter -> like #71 
  - [x] Set location of a device -> #235 
  - [x] Page to add a new device. -> #332 
  - [x] Page to edit a device (can likely reuse a lot from the add device form) -> #584 
  - [x] Page to view streaming data of the device -> #691

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1067 by @bafonins

**Comment by kschiffer** [comment]
See also #47.

**Comment by kschiffer** [comment]
🎉

**Comment by johanstokking** [comment]
Nice!!
