### ISSUE TITLE
Console support for API keys of entities

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#251]
**Summary:**

The console should provide functionality to manage API keys of top-level entities:

- [x] applications #142 
- [x] gateways
- [x] organizations (https://github.com/TheThingsNetwork/lorawan-stack/issues/1205)
- [ ] users

This includes:

- Listing API Keys
- Adding new API keys
- Updating API Key rights
- Removing API Keys

**What is already there? What do you see now?**

Applications API key management #171 

**What is missing? What do you want to see?**

- [x] Entry in the side navigation when managing API keys for an application
- [x] Entry in the side navigation when managing API keys for a gateway
- [x] Entry in the side navigation when managing API keys for an organization
- [ ] Entry in the side navigation when managing API keys for a user
- [x] Main API keys page within the applications section
- [x] Main API keys page within the gateways section
- [x] Main API keys page within the organizations section
- [ ] Main API keys page within the user settings
- [x] Page to update/remove API key rights for applications
- [x] Page to update/remove API key rights for gateways
- [x] Page to update/remove API key rights for organizations
- [ ] Page to update/remove API key rights for users
