### ISSUE TITLE
Console unclarities

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2529]
#### Summary
Overview of features that need to be clarified in the Console.

#### Why do we need this?
Improve UI & UX

#### Overview

- [ ] `No-prefix` - Unclear what it is. It's also not possible to be set. #2542 
  <img width="689" alt="Screenshot 2020-05-13 at 10 55 22" src="https://user-images.githubusercontent.com/17290639/81792845-e60b5200-9508-11ea-9e9b-5a7b46ef0c4a.png">

- [ ] `Attributes` - Unclear what it is and how to set it.
  *Link to documentation needed*
  <img width="683" alt="Screenshot 2020-05-13 at 10 59 14" src="https://user-images.githubusercontent.com/17290639/81792822-dee44400-9508-11ea-9577-da62d8278262.png">

- [x] External Join Server - unclear why this is enabled by default
  *Description / link to documentation needed* --> #2593
  <img width="296" alt="Screenshot 2020-05-13 at 11 27 59" src="https://user-images.githubusercontent.com/17290639/81795831-df7ed980-950c-11ea-9e96-da51ee09cbbe.png">

- [ ] Unclear if/how Location data of devices is used. #3124
  *Description needed*
  <img width="514" alt="Screenshot 2020-05-13 at 11 32 57" src="https://user-images.githubusercontent.com/17290639/81796301-8a8f9300-950d-11ea-9fa2-e5fbc6afae38.png">

- [x] Frequency plans with/without `(TTN)` #2543 & #2421
  *Description needed*
  <img width="698" alt="Screenshot 2020-05-13 at 11 38 32" src="https://user-images.githubusercontent.com/17290639/81796902-58cafc00-950e-11ea-88be-62029fb8e57a.png">

- [ ] Gateway status pubic - where and when is this publicly displayed?
  *Description update needed*
<img width="531" alt="Screenshot 2020-05-13 at 11 42 40" src="https://user-images.githubusercontent.com/17290639/81797317-e4448d00-950e-11ea-8164-b9eaa7527482.png">

**Comment by johanstokking** [comment]
Thanks. @laurensslats what exactly is open for discussion?

**Comment by kschiffer** [comment]
> - [ ] External Join Server - unclear why this is enabled by default
  *Description / link to documentation needed*
  <img width="296" alt="Screenshot 2020-05-13 at 11 27 59" src="https://user-images.githubusercontent.com/17290639/81795831-df7ed980-950c-11ea-9e96-da51ee09cbbe.png">
Any info on this @johanstokking / @htdvisser ?

**Comment by htdvisser** [comment]
I don't know. To me it also doesn't make sense to use external join servers by default.

**Comment by johanstokking** [comment]
This is too much wishful thinking on my side I think. Let's change the default to not use external JS, unless the majority of new devices are indeed provisioned on a Join Server already.

**Comment by kschiffer** [comment]
cc @bafonins

**Comment by johanstokking** [comment]
Closing; looks like all issues are addressed individually. If not, please file the concerning issues. This umbrella issue is just a list of issues which makes it hard to plan and triage, so we close it.
