### ISSUE TITLE
Console support for collaborators for entities

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#27]
**Summary:**

The console should provide functionality to manage collaborators of top-level entities:

- [x] applications (https://github.com/TheThingsIndustries/lorawan-stack/issues/1065)
- [ ] OAuth clients (#4300 )
- [x] gateways (https://github.com/TheThingsIndustries/lorawan-stack/issues/1068)
- [x] organizations (https://github.com/TheThingsNetwork/lorawan-stack/issues/1205)

This includes:

- Listing collaborators
- Adding collaborators
- Updating collaborator rights
- Removing collaborators

**What is already there? What do you see now?**

Screen design for the collaborators page within the applications section

**What is missing? What do you want to see?**

- [x] Entry in the side navigation when managing collaborators for an application
- [ ] Entry in the side navigation when managing collaborators for an OAuth client
- [x] Entry in the side navigation when managing collaborators for a gateway
- [x] Entry in the side navigation when managing collaborators for an organization
- [x] Main collaborators page within the applications section
- [ ] Main collaborators page within the clients section
- [x] Main collaborators page within the gateways section
- [x] Main collaborators page within the organizations section
- [x] Page to update/remove collaborator rights for applications
- [ ] Page to update/remove collaborator rights for client
- [x] Page to update/remove collaborator rights for gateways
- [x] Page to update/remove collaborator rights for organizations

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1069 by @bafonins

**Comment by kschiffer** [comment]
Closed this since the remaining issue #4300 should be sufficient now.
