### ISSUE TITLE
Improve `<Form />` component

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3450]
#### Summary

There a bunch of improvements we can implement for the `<Form />` component.

#### Why do we need this?

Performance, UX improvements.

#### What is missing? What do you want to see?

- [ ] Resolve https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.10/pkg/webui/components/form/field/index.js#L128-L129
- [ ] Update `formik` and `yup` to the latest versions.
- [ ] Do not rerender all fields when processing a single input:
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/16374166/98527652-f1ef8b00-2283-11eb-8d2a-f3f1d01b7130.gif)
- [ ] Adjust field error/warning styles to avoid shifting all content below the errored field:
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/16374166/98528314-ce791000-2284-11eb-9877-9f8e6f6e9776.gif)
- [ ] Do not remove error messages after `onBlur` event on fields without any changes to the input before the next submission:
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/16374166/98528865-90302080-2285-11eb-8b21-58e05126a727.gif)

#### How do you propose to test this?

Manual testing

#### Can you do this yourself and submit a Pull Request?

yes
