### ISSUE TITLE
Improve `<Modal />` component

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3451]
#### Summary

There a bunch of improvements we can implement for the `<Modal />` component.

#### Why do we need this?

Better UX

#### What is missing? What do you want to see?

- [x] Disable scrolling of background content when the `<Modal />` component is visible
- [x] Add functionality to cancel, approve the modal actions using only keyboard (`Esc` and `Enter` keys).
- [x] Add aria attributes for a11y

#### How do you propose to test this?

Manual

#### Can you do this yourself and submit a Pull Request?

yes
