### ISSUE TITLE
Console MVP

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#629]
#### Summary
This is an umbrella issue to track the status of the Console MVP.

#### Status
- [x] Applications
  - [x] Application List
  - [x] Add Applications
  - [x] Overview
  - [x] End Device List ⟶ #644  
  - [x] End Devices ⟶ #25 
    - [x] Add End Devices ⟶ #573 
    - [x] Overview ⟶ #376 
    - [x] Payload Formats ⟶ #71, #778
    - [x] End Device Event/Data Stream ⟶ #691
    - [x] General Settings (Edit End Devices) ⟶ #624 
    - [x] Set Location (without maps) ⟶ #643 
  - [x] Application Event/Data Stream ⟶ #522 
  - [x] Linking ⟶ #214 
  - [x] Payload Formats ⟶ #71, #742 
  - [x] Integrations (webhooks) ⟶ #686 
  - [x] API Keys ⟶ #142 
  - [x] Collaborators ⟶ #449 
  - [x] General Settings (Edit Applications)
- [x] Gateways ⟶ #26 
  - [x] Gateway List (only stubbed atm, needs issue)
  - [x] Overview ⟶ #243 
  - [x] Add Gateways ⟶ #628 
  - [x] API Keys ⟶ #660 
  - [x] Set Location (without maps) ⟶ #713 
  - [x] Gateway Event/Data Stream ⟶ #648, #748
  - [x] General Settings (Edit Gateways) ⟶ #763 
  - [x] Collaborators ⟶ #777 
- [x] SDK ⟶ #30 
  - [x] Entity CRUD
    - [x] Applications
    - [x] End Devices ⟶ #278 
    - [x] Gateways ⟶ #620 
  - [x] Stack Config ⟶ #588 
    - [x] Frequency Plans ⟶ #588 
  - [x] Event Streams
    - [x] Applications ⟶ #522 
    - [x] End Devices ⟶ via #695
    - [x] Gateways ⟶ #748

- [ ] Overall
  - [ ] Internal testing and debugging ⟶ needs coordination, cc @johanstokking, @htdvisser 
  - [x] Proper error handling ⟶ #667 
  - [x] Streamline page titles ⟶ #619 
  - [ ] Styling finish ⟶ #875, ~~#923~~
  - [x] Build starting point for overview page ⟶ #928 
  - [x] User Login (not exactly console)
  - [x] User Registration (not exactly console)
  - [x] Authorization screen (not exactly console)

Undecided whether in MVP:
- Profile Settings of the user
- Organizations management
- First release of SDK

@bafonins @htdvisser @johanstokking please check and add whatever you find missing. I will try to keep this up to date, any help welcome.

**Comment by johanstokking** [comment]
Can we add some basic overview to the scope of MVP?

**Comment by kschiffer** [comment]
Yes. Updated the description.

**Comment by kschiffer** [comment]
I think we can consider this done now since the console has been "released" with 3.1.0. Remaining issues are taken care of.
