### ISSUE TITLE
Improve user experience of events in The Things Stack Console

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#7341]
### Summary

This issue consolidates improvements to the user experience of events in The Things Stack Console.

### Current Situation

We have a pretty nice events view for end Devices, applications and gateways.

### Why do we need this? Who uses it, and when?

We need a few improvements to improve the user experience when working with events in the console.

#### Low Hanging Fruit (UX only updates)

- [ ] https://github.com/TheThingsNetwork/lorawan-stack/issues/3718
- [ ] https://github.com/TheThingsNetwork/lorawan-stack/issues/3812
- [ ] https://github.com/TheThingsNetwork/lorawan-stack/issues/7342
- [ ] https://github.com/TheThingsNetwork/lorawan-stack/issues/3719

#### Next up items

- [ ] https://github.com/TheThingsNetwork/lorawan-stack/issues/7314
- [ ] https://github.com/TheThingsIndustries/lorawan-stack-support/issues/960

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Validation

- [ ] The feature is tested in a staging environment.
- [ ] The feature is documented in [The Things Stack Documentation](https://www.thethingsindustries.com/docs/)

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).
