### ISSUE TITLE
Update console/oauth dependencies

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#790]
#### Summary

We should update react and react related dependencies.

#### Why do we need this?

Keep up with the latest versions of dependencies. What is more, the [16.6](https://github.com/facebook/react/releases/tag/v16.6.0) version adds several useful features, namely `React.memo()` and `contextType`.

#### What is already there? What do you see now?

Old versions

#### What is missing? What do you want to see?

Updated dependencies
deps:
- [x] react
- [x] react-dom
- [x] redux
- [x] redux-logic
- [x] connected-react-router (https://github.com/TheThingsNetwork/lorawan-stack/pull/1139)
- [x] react-redux (https://github.com/TheThingsNetwork/lorawan-stack/pull/1139)
- [x] formik, v2 of the library introduces variety of cool features, but is still in development
- [x] react-intl (https://github.com/TheThingsNetwork/lorawan-stack/pull/1139)
 
dev-deps:
- [x] storybook, there v5 out and looks very nice, however i can imagine that we would have to change our storybook config ⟶ via #793
- [x] various storybook updates for v5 ⟶ via #793
- [x] eslint v5 ⟶ via #793
- [x] js-yaml v3 (fixes vulnerability) ⟶ via #793
- [x] css-loader v2 ⟶ via #793
#### Environment

browser

#### How do you propose to implement this?

Update deps in `package.json` and make sure nothing breaks

#### Can you do this yourself and submit a Pull Request?

yes. would be nice to update major libraries before the console mvp

cc @kschiffer feel free to add/update stuff

**Comment by kschiffer** [comment]
I'm actually partially working on this atm via #772, at least as far as some devDeps (including storybook) go. Should see a PR soon.

**Comment by kschiffer** [comment]
Description updated

**Comment by bafonins** [comment]
Description updated
